version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  network_mode: host
  build: &build_settings
    context: ..
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "${PYTHON_VERSION:-3.7}"
      GCC_VERSION: "${GCC_VERSION:-9}"
      RAPIDS_HOME: "${RAPIDS_HOME:-$PWD}"
      COMPOSE_HOME: "${COMPOSE_HOME:-$PWD/compose}"
      CUDA_VERSION: "${CUDA_VERSION:-11.2.0}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"
      PARALLEL_LEVEL: "${PARALLEL_LEVEL:-4}"
      USE_FISH_SHELL: "${USE_FISH_SHELL:-}"
  tty: true
  environment:
    TERM: "${TERM}"
    # LC_ALL: C
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$_UID}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
    DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$_UID/bus}"
    QT_AUTO_SCREEN_SCALE_FACTOR: 0
    NVIDIA_DRIVER_CAPABILITIES: all
  cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
  security_opt:
    - apparmor=unconfined
    - seccomp="${COMPOSE_HOME:-$PWD/compose}/etc/settings/docker-seccomp-with-perf.json"
  depends_on:
    - apt-cacher-ng

services:

  rapids:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rapids:cuda-${CUDA_VERSION:-11.2.0}
    build:
      <<: *build_settings
      dockerfile: "${COMPOSE_HOME:-$PWD/compose}/dockerfiles/rapids.Dockerfile"
    volumes:
      - &rmm "${RAPIDS_HOME:-$PWD}/rmm:${RAPIDS_HOME:-$PWD}/rmm"
      - &cudf "${RAPIDS_HOME:-$PWD}/cudf:${RAPIDS_HOME:-$PWD}/cudf"
      - &cuml "${RAPIDS_HOME:-$PWD}/cuml:${RAPIDS_HOME:-$PWD}/cuml"
      - &raft "${RAPIDS_HOME:-$PWD}/raft:${RAPIDS_HOME:-$PWD}/raft"
      - &compose "${COMPOSE_HOME:-$PWD/compose}:${COMPOSE_HOME:-$PWD/compose}"
      - &cugraph "${RAPIDS_HOME:-$PWD}/cugraph:${RAPIDS_HOME:-$PWD}/cugraph"
      - &cuspatial "${RAPIDS_HOME:-$PWD}/cuspatial:${RAPIDS_HOME:-$PWD}/cuspatial"
      - &bashrc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bashrc:${RAPIDS_HOME:-$PWD}/.bashrc"
      - &colornvcc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/colornvcc:/usr/bin/nvcc"
      - &dot_colornvccrc "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.colornvccrc:${RAPIDS_HOME:-$PWD}/.colornvccrc"
      - &dot_local "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.local:${RAPIDS_HOME:-$PWD}/.local"
      - &dot_config "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.config:${RAPIDS_HOME:-$PWD}/.config"
      - &dot_ipython "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.ipython:${RAPIDS_HOME:-$PWD}/.ipython"
      - &bash_history "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bash_history:${RAPIDS_HOME:-$PWD}/.eternal_bash_history"
      - &etc_localtime "/etc/localtime:/etc/localtime"
      - &etc_timezone "/etc/timezone:/etc/timezone"
      - &etc_fonts "/etc/fonts:/etc/fonts:ro"
      - &x11_socket "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - &usr_share_fonts "/usr/share/fonts:/usr/share/fonts:ro"
      - &dbus_system_bus_socket "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
      - &xdg_runtime_dir "${XDG_RUNTIME_DIR:-/run/user/$_UID}:${XDG_RUNTIME_DIR:-/run/user/$_UID}"

  notebooks:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/notebooks:cuda-${CUDA_VERSION:-11.2.0}
    build:
      <<: *build_settings
      dockerfile: "${COMPOSE_HOME:-$PWD/compose}/dockerfiles/notebooks.Dockerfile"
    volumes:
      - *rmm
      - *cudf
      - *cuml
      - *raft
      - *compose
      - *cugraph
      - *cuspatial
      - *bashrc
      - *colornvcc
      - *dot_colornvccrc
      - *dot_local
      - *dot_config
      - *dot_ipython
      - *bash_history
      - *etc_localtime
      - *etc_timezone
      - *etc_fonts
      - *x11_socket
      - *usr_share_fonts
      - *xdg_runtime_dir
      - *dbus_system_bus_socket
      - &jupyter "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/.jupyter:${RAPIDS_HOME:-$PWD}/.jupyter"
      - &notebooks_contrib "${RAPIDS_HOME:-$PWD}/notebooks-contrib:${RAPIDS_HOME:-$PWD}/notebooks/contrib"
      - &notebooks_sandbox "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/sandbox:${RAPIDS_HOME:-$PWD}/notebooks/sandbox"

  apt-cacher-ng:
    restart: always
    image: sameersbn/apt-cacher-ng:3.1-3
    ports:
    - "3142:3142"
    volumes:
    - apt-cache:/var/cache/apt-cacher-ng

volumes:
  apt-cache:
