version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  network_mode: host
  build: &build_settings
    context: ..
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "3.7"
      GCC_VERSION: "${GCC_VERSION:-5}"
      CXX_VERSION: "${CXX_VERSION:-5}"
      RAPIDS_HOME: "${RAPIDS_HOME:-$PWD}"
      COMPOSE_HOME: "${COMPOSE_HOME:-$PWD/compose}"
      CUDA_VERSION: "${CUDA_VERSION:-10.0}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"
      PARALLEL_LEVEL: "${PARALLEL_LEVEL:-4}"

services:

  rapids:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rapids:cuda-${CUDA_VERSION:-10.0}
    build:
      <<: *build_settings
      dockerfile: ${COMPOSE_HOME:-$PWD/compose}/dockerfiles/rapids.Dockerfile
    tty: true
    environment:
      - TERM=xterm-256color
      - NVIDIA_DRIVER_CAPABILITIES=all
    cap_add:
      - SYS_PTRACE
    volumes:
      - &rmm "${RAPIDS_HOME:-$PWD}/rmm:${RAPIDS_HOME:-$PWD}/rmm"
      - &cudf "${RAPIDS_HOME:-$PWD}/cudf:${RAPIDS_HOME:-$PWD}/cudf"
      - &cuml "${RAPIDS_HOME:-$PWD}/cuml:${RAPIDS_HOME:-$PWD}/cuml"
      - &raft "${RAPIDS_HOME:-$PWD}/raft:${RAPIDS_HOME:-$PWD}/raft"
      - &compose "${COMPOSE_HOME:-$PWD/compose}:${COMPOSE_HOME:-$PWD/compose}"
      - &cugraph "${RAPIDS_HOME:-$PWD}/cugraph:${RAPIDS_HOME:-$PWD}/cugraph"
      - &cuspatial "${RAPIDS_HOME:-$PWD}/cuspatial:${RAPIDS_HOME:-$PWD}/cuspatial"
      - &ptvsd_logs "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/log:/var/log/ptvsd"
      - &bashrc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bashrc:${RAPIDS_HOME:-$PWD}/.bashrc"
      - &colornvcc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/colornvcc:/usr/bin/nvcc"
      - &colornvccrc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.colornvccrc:${RAPIDS_HOME:-$PWD}/.colornvccrc"
      - &bash_history "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bash_history:${RAPIDS_HOME:-$PWD}/.bash_history"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    depends_on:
      - apt-cacher-ng

  notebooks:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/notebooks:cuda-${CUDA_VERSION:-10.0}
    build:
      <<: *build_settings
      dockerfile: ${COMPOSE_HOME:-$PWD/compose}/dockerfiles/notebooks.Dockerfile
    tty: true
    environment:
      - TERM=xterm-256color
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "5678:5678"
      - "8888:8888"
    volumes:
      - *ptvsd_logs
      - *rmm
      - *cudf
      - *cuml
      - *raft
      - *compose
      - *cugraph
      - *cuspatial
      - *bashrc
      - *colornvcc
      - *colornvccrc
      - *bash_history
      - &jupyter "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/.jupyter:${RAPIDS_HOME:-$PWD}/.jupyter"
      - &notebooks_core "${RAPIDS_HOME:-$PWD}/notebooks:${RAPIDS_HOME:-$PWD}/notebooks/core"
      - &notebooks_sandbox "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/sandbox:${RAPIDS_HOME:-$PWD}/notebooks/sandbox"
      - &notebooks_extended "${RAPIDS_HOME:-$PWD}/notebooks-contrib:${RAPIDS_HOME:-$PWD}/notebooks/contrib"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    depends_on:
      - apt-cacher-ng

  apt-cacher-ng:
    restart: always
    image: sameersbn/apt-cacher-ng:3.1-3
    ports:
    - "3142:3142"
    volumes:
    - apt-cache:/var/cache/apt-cacher-ng

volumes:
  apt-cache:
